### ISSUE TITLE
metadata

### ISSUE THREAD

**Issue by srinisri91** [naveenkumar-j/tomato-leaf-disease-prediction-ml-andriodapp#3]
please give me the metadata also the after clicking the predict the app closes can you help me out with this?

**Comment by srinivasan504** [comment]
Bro actually i would like to add the name of the disease alone can you help me out with it?

**Comment by naveenkumar-j** [comment]
Hi @srinivasan504, Please refer this youtube video to understand how to build this app: [youtube link](https://www.youtube.com/watch?v=fqu1y7YvVWA)

**Comment by naveenkumar-j** [comment]
Hi @srinisri91, you have to train the model. Please refer this youtube video to understand how to build your own model: [youtube link](https://www.youtube.com/watch?v=fqu1y7YvVWA). Thank you.
